#!/bin/bash

export PATH=/usr/local/cuda-10.2/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH
#source /opt/ros/foxy/install/setup.bash
#source /usr/share/colcon_cd/function/colcon_cd.sh
#export _colcon_cd_root=~/ros2_install
source /opt/ros/melodic/setup.bash

export ROS_HOSTNAME=192.168.1.100
export ROS_MASTER_URI=http://192.168.1.5:11311

cd /home/jkk-natlab/perception-stack/
source install/setup.bash
cd /home/jkk-natlab/perception-stack/src/fusion/scripts
python3 fusion_np.py
